/*
* generated by Xtext
*/
package org.eclipse.scout.saml.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.scout.saml.services.SamlGrammarAccess;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

import com.google.inject.Inject;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SamlProposalProvider extends AbstractSamlProposalProvider {

  @Inject
  SamlGrammarAccess access;

  @Override
  public void completeLogicElement_Placement(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
    /*List<Keyword> completions = getAllContentsOfType(access.getRunAtTypeRule().getAlternatives(), Keyword.class);
    for (Keyword keyword : completions) {
      acceptor.accept(createCompletionProposal(keyword.getValue(), context));
    }*/
  }
}
