package org.eclipse.scout.saml.tests;

import com.google.inject.Inject;
import com.google.inject.Provider;
import org.eclipse.scout.saml.SamlInjectorProvider;
import org.eclipse.scout.saml.saml.Model;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.junit4.validation.ValidationTestHelper;
import org.eclipse.xtext.resource.XtextResourceSet;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(value = XtextRunner.class)
@InjectWith(value = SamlInjectorProvider.class)
@SuppressWarnings("all")
public class ComplexFormTests {
  @Inject
  private ParseHelper<Model> _parseHelper;
  
  @Inject
  private ValidationTestHelper _validationTestHelper;
  
  @Inject
  private Provider<XtextResourceSet> resourceSetProvider;
  
  @Test
  public void testTextRefOverFiles() {
    try {
      final XtextResourceSet resourceSet = this.resourceSetProvider.get();
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("module ch.raiffeisen.dialba.common");
      _builder.newLine();
      _builder.newLine();
      _builder.append("translation AboutMenu de=\"&Info...\"");
      _builder.newLine();
      _builder.append("translation Abschluss de=\"Abschluss\"");
      _builder.newLine();
      _builder.append("translation AbsichernRefinanz de=\"Absichern / Refinanz.\"");
      _builder.newLine();
      _builder.append("translation AlteNeueKONr de=\"Alte / Neue KO-Nr.\"");
      _builder.newLine();
      _builder.append("translation Anlegen de=\"Anlegen\"");
      _builder.newLine();
      _builder.append("translation ApplicationTitle de=\"Meine Applikation\"");
      _builder.newLine();
      _builder.append("translation Art de=\"Art\"");
      _builder.newLine();
      _builder.append("translation AuthorizationFailed de=\"Zugriff verweigert\"");
      _builder.newLine();
      _builder.append("translation Basiskredit de=\"Basiskredit\"");
      _builder.newLine();
      _builder.append("translation Bearbeiten de=\"Bearbeiten\"");
      _builder.newLine();
      _builder.append("translation BemF4 de=\"Bem.                                   F4\"");
      _builder.newLine();
      _builder.append("translation BeratungsModus de=\"Beratungs-Modus\"");
      _builder.newLine();
      _builder.append("translation BetragSpesen de=\"Betrag / Spesen\"");
      _builder.newLine();
      _builder.append("translation Buchungstext1 de=\"Buchungstext 1\"");
      _builder.newLine();
      _builder.append("translation Buchungstext2 de=\"Buchungstext 2\"");
      _builder.newLine();
      _builder.append("translation Buchungstext3 de=\"Buchungstext 3\"");
      _builder.newLine();
      _builder.append("translation CHF de=\"CHF\"");
      _builder.newLine();
      _builder.append("translation ContactVendorMenu de=\"BSI kontaktieren\"");
      _builder.newLine();
      _builder.append("translation DIALBA2020 de=\"DIALBA2020\"");
      _builder.newLine();
      _builder.append("translation DIALBA2020Title de=\"DIALBA2020\"");
      _builder.newLine();
      _builder.append("translation DatumEmission de=\"Datum / Emission\"");
      _builder.newLine();
      _builder.append("translation DepotText de=\"Depot\"");
      _builder.newLine();
      _builder.append("translation DepotCode de=\"Depot \"");
      _builder.newLine();
      _builder.append("translation DepotTwin de=\"DepotTwin\"");
      _builder.newLine();
      _builder.append("translation Dienste de=\"Dienste\"");
      _builder.newLine();
      _builder.append("translation EDossierStarten de=\"eDossier starten\"");
      _builder.newLine();
      _builder.append("translation ESC de=\"Ende               ESC\"");
      _builder.newLine();
      _builder.append("translation Emissionsabgabe de=\"Emissionsabgabe\"");
      _builder.newLine();
      _builder.append("translation EndeESC de=\"Ende                                   ESC\"");
      _builder.newLine();
      _builder.append("translation ExitMenu de=\"&Beenden\"");
      _builder.newLine();
      _builder.append("translation ExportToExcelDiagramMenu de=\"Ausgabe in Excel &Diagramm\"");
      _builder.newLine();
      _builder.append("translation ExportToExcelMenu de=\"Ausgabe in &Excel\"");
      _builder.newLine();
      _builder.append("translation FiT de=\"FiT\"");
      _builder.newLine();
      _builder.append("translation FileMenu de=\"&Datei\"");
      _builder.newLine();
      _builder.append("translation Finanzieren de=\"Finanzieren\"");
      _builder.newLine();
      _builder.append("translation FondsSparplan de=\"Fonds-Sparplan\"");
      _builder.newLine();
      _builder.append("translation Funktionen de=\"Funktionen \"");
      _builder.newLine();
      _builder.append("translation GesamtobligoEN de=\"Gesamtobligo\"");
      _builder.newLine();
      _builder.append("translation HelpMenu de=\"&Hilfe\"");
      _builder.newLine();
      _builder.append("translation IndexHilfe de=\"Index Hilfe\"");
      _builder.newLine();
      _builder.append("translation Info de=\"Info\"");
      _builder.newLine();
      _builder.append("translation InfoF7 de=\"Info                                     F7\"");
      _builder.newLine();
      _builder.append("translation InfoUmschF7 de=\"Info (Umsch + F7)\"");
      _builder.newLine();
      _builder.append("translation Inhaber de=\"Inhaber\"");
      _builder.newLine();
      _builder.append("translation KOEmission de=\"KO Emission\"");
      _builder.newLine();
      _builder.append("translation KOEmissionMenu de=\"KO Emission...\"");
      _builder.newLine();
      _builder.append("translation KOEmmissionTc200 de=\"200 KO Emission\"");
      _builder.newLine();
      _builder.append("translation Kassenobligationen de=\"Kassenobligationen\"");
      _builder.newLine();
      _builder.append("translation KassenobligationenArt de=\"Kassenobligationen Art\"");
      _builder.newLine();
      _builder.append("translation KontoIBAN de=\"Konto / IBAN\"");
      _builder.newLine();
      _builder.append("translation Kontobelastung de=\"Kontobelastung\"");
      _builder.newLine();
      _builder.append("translation Kreditkarte de=\"Kreditkarte\"");
      _builder.newLine();
      _builder.append("translation Kunde de=\"Kunde\"");
      _builder.newLine();
      _builder.append("translation Kurzbezeichnung de=\"Kurzbezeichnung\"");
      _builder.newLine();
      _builder.append("translation LaufzeitText de=\"Laufzeit\"");
      _builder.newLine();
      _builder.append("translation MitTiteldruck de=\"Mit Titeldruck\"");
      _builder.newLine();
      _builder.append("translation Namen de=\"Namen\"");
      _builder.newLine();
      _builder.append("translation NamenMitglied de=\"Namen Mitglied\"");
      _builder.newLine();
      _builder.append("translation ObligoF5 de=\"Obligo                                F5\"");
      _builder.newLine();
      _builder.append("translation ProgrammSuchenUmschF2EN de=\"Programm suchen (Umsch + F2)\"");
      _builder.newLine();
      _builder.append("translation RAIweb de=\"RAIweb\"");
      _builder.newLine();
      _builder.append("translation RIAG de=\"RIAG\"");
      _builder.newLine();
      _builder.append("translation RaiffeisenEBanking de=\"Raiffeisen E-Banking\"");
      _builder.newLine();
      _builder.append("translation Schnellzugriff de=\"Schnellzugriff...\"");
      _builder.newLine();
      _builder.append("translation SchnellzugriffForm de=\"Schnellzugriff\"");
      _builder.newLine();
      _builder.append("translation SpezialzinsF2 de=\"Spezialzins                         F2\"");
      _builder.newLine();
      _builder.append("translation StornoF6 de=\"Storno                                F6\"");
      _builder.newLine();
      _builder.append("translation TC0 de=\"TC ...\"");
      _builder.newLine();
      _builder.append("translation TC de=\"TC\"");
      _builder.newLine();
      _builder.append("translation TCButton de=\"...\"");
      _builder.newLine();
      _builder.append("translation Test de=\"Test\"");
      _builder.newLine();
      _builder.append("translation TestForm de=\"TestForm\"");
      _builder.newLine();
      _builder.append("translation ToolsMenu de=\"&Extras\"");
      _builder.newLine();
      _builder.append("translation TransactionsCodeForKOEmission de=\"200 KO Emission\"");
      _builder.newLine();
      _builder.append("translation Transaktionscode de=\"TC\"");
      _builder.newLine();
      _builder.append("translation TransaktionscodeTwin de=\"TransaktionscodeTwin\"");
      _builder.newLine();
      _builder.append("translation UKVKF3 de=\"UK/VK                                 F3\"");
      _builder.newLine();
      _builder.append("translation UKVollmachtenkarte de=\"UK / Vollmachtenkarte\"");
      _builder.newLine();
      _builder.append("translation Valorennummer de=\"Valorennummer\"");
      _builder.newLine();
      _builder.append("translation Versicherung de=\"Versicherung\"");
      _builder.newLine();
      _builder.append("translation Vorsorgen de=\"Vorsorgen\"");
      _builder.newLine();
      _builder.append("translation Zahlen de=\"Zahlen\"");
      _builder.newLine();
      _builder.append("translation Zentralregister de=\"Zentralregister\"");
      _builder.newLine();
      _builder.append("translation ZentralregisterUmschF12 de=\"Zentralregister (Umsch + F12) \"");
      _builder.newLine();
      _builder.append("translation ZinssatzText de=\"Zinssatz\"");
      _builder.newLine();
      _builder.append("translation ZinstermAuslauf de=\"Zinsterm / Auslauf\"");
      _builder.newLine();
      _builder.append("translation ZregNumber de=\"ZREG-Nr.\"");
      _builder.newLine();
      _builder.append("translation ZregQuickSearchForm de=\"Zreg Schnellsuche\"");
      _builder.newLine();
      _builder.append("translation anErrorOccured de=\"Ein Fehler ist aufgetreten\"");
      _builder.newLine();
      _builder.append("translation loggingFileNotFound de=\"Das Logging wurde nicht korrekt inizilisiert. Bitte Kevin kontaktieren...\"");
      _builder.newLine();
      _builder.append("translation loggingMalformedUrl de=\"Das Logging wurde nicht korrekt inizilisiert. Bitte Kevin kontaktieren...\"");
      _builder.newLine();
      _builder.append("translation someErrorsOccured de=\"Folgende Fehler sind aufgetreten\"");
      _builder.newLine();
      _builder.newLine();
      _builder.newLine();
      _builder.append("// ========================");
      _builder.newLine();
      _builder.append("// CODE TYPES");
      _builder.newLine();
      _builder.append("// ========================");
      _builder.newLine();
      _builder.append("code KOArt id=1112");
      _builder.newLine();
      _builder.append("code KOLaufzeit id=9687");
      _builder.newLine();
      _builder.append("code KOTiteldruck id=2569");
      _builder.newLine();
      _builder.newLine();
      _builder.newLine();
      _builder.append("// ========================");
      _builder.newLine();
      _builder.append("// LOOKUP CALLS & SERVICES");
      _builder.newLine();
      _builder.append("// ========================");
      _builder.newLine();
      _builder.append("lookup DepotNumber {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("logic placement=server {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("\"private LookupRow[] createDummyData() {");
      _builder.newLine();
      _builder.append("  \t\t  ");
      _builder.append("return new LookupRow[]{new LookupRow(new DepotId(), \\\"Depot id 1\\\"), new LookupRow(new DepotId(), \\\"Depot id 2\\\"), new LookupRow(new DepotId(), \\\"Depot id 3\\\")};");
      _builder.newLine();
      _builder.append("  \t\t");
      _builder.append("}\"");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("logic event=all placement=server {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("\"return createDummyData();\"");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("lookup OldObliNumber {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("logic event=all placement=server {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("\"return new LookupRow[]{");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("new org.eclipse.scout.rt.shared.services.lookup.LookupRow(1L, \\\"Value 1\\\"),");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("new org.eclipse.scout.rt.shared.services.lookup.LookupRow(2L, \\\"Value 2\\\"),");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("new org.eclipse.scout.rt.shared.services.lookup.LookupRow(3L, \\\"Value 3\\\")};");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("\"");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("lookup KontoByZrnr {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("logic placement=server { ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("\"private LookupRow[] createDummyData() {");
      _builder.newLine();
      _builder.append("  \t\t  ");
      _builder.append("return new LookupRow[]{new LookupRow(new KontoData(), \\\"KontoData id 1\\\"), new LookupRow(new KontoData(), \\\"KontoData id 2\\\"), new LookupRow(new KontoData(), \\\"KontoData id 3\\\")};");
      _builder.newLine();
      _builder.append("  \t\t");
      _builder.append("}\"");
      _builder.newLine();
      _builder.append("  \t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("logic event=all placement=server {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("\"return createDummyData();\"");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("// ========================");
      _builder.newLine();
      _builder.append("// UI TEMPLATE DEFINITIONS");
      _builder.newLine();
      _builder.append("// ========================");
      _builder.newLine();
      _builder.append("template zreg_sequence_box definition=\"java.lang.Integer\"");
      _builder.newLine();
      _builder.newLine();
      _builder.newLine();
      _builder.append("// ========================");
      _builder.newLine();
      _builder.append("// FORMS");
      _builder.newLine();
      _builder.append("// ========================");
      _builder.newLine();
      _builder.append("form Rka001_gen modal=true title=KOEmission subtitle=DIALBA2020 {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("logic EvalForm placement=client {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("\"evaluateZinstermFields();");
      _builder.newLine();
      _builder.append("\t     ");
      _builder.append("evaluateBuchungstext1And2();\"");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("logic ZregAsMasterField placement=inline {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("\"@Override");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("protected Class<? extends IValueField> getConfiguredMasterField() {");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("return getZregBoxField().getZregNumberField().getClass();");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("        ");
      _builder.append("@Override");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("protected boolean getConfiguredMasterRequired() {");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("return true;");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("}\"");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("logic placement=server event=new_store {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("\"System.out.println(\\\"server call create\\\");");
      _builder.newLine();
      _builder.append("\t\t ");
      _builder.append("return formData;\"");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("logic placement=client {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("\"private void evaluateBuchungstext1And2() throws ProcessingException {");
      _builder.newLine();
      _builder.append("\t        ");
      _builder.append("System.out.println(\\\"client method evaluateBuchungstext1And2\\\");\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("private void evaluateZinstermFields() {");
      _builder.newLine();
      _builder.append("\t        ");
      _builder.append("System.out.println(\\\"client method evaluateZinstermFields\\\");");
      _builder.newLine();
      _builder.append("\t    ");
      _builder.append("}\"");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("group_box Tool label_visible=false border_decoration=empty border_visible=false {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("button FunktionenButton text=Funktionen process_button=false {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("menu EndeESCMenu text=EndeESC");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("menu SpezialzinsF2Menu text=SpezialzinsF2");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("menu UKVKF3Menu text=UKVKF3");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("menu BemF4Menu text=BemF4");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("menu ObligoF5Menu text=ObligoF5");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("menu StornoF6Menu text=StornoF6");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("menu InfoF7Menu text=InfoF7");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box TransaktionscodeSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("string BuchungsCode text=Transaktionscode enabled=false {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic placement=inline event=format_value {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("\"return TEXTS.get(\\\"TransactionsCodeForKOEmission\\\");\"");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("custom_field ZregBox super_type=zreg_sequence_box text=Zentralregister {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("logic event=init placement=client {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("\"System.out.println(\\\"init zregboxfield\\\");\"");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("logic placement=inline {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("\"@Override");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("public ch.raiffeisen.dialba.common.shared.services.process.ZregSequenceBoxDataAbs getBoxData() {");
      _builder.newLine();
      _builder.append("                ");
      _builder.append("return new Rka001_genFormData().getZregBox();");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("}\"");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box KoArtSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("smartfield KoArt text=Art mandatory=true value_type=\"java.lang.Integer\" code=KOArt");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box LaufzeitSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("smartfield Laufzeit text=LaufzeitText mandatory=true code=KOLaufzeit value_type=\"java.lang.Integer\" {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic event=changed placement=server {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("\"System.out.println(\\\"server call LaufzeitfieldChanged\\\");");
      _builder.newLine();
      _builder.append("\t\t\t\t ");
      _builder.append("return formData;\"");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic event=changed exec=EvalForm");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box ValorSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("string Valor text=Valorennummer enabled=false");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box ZinssatzSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("double Zinssatz text=ZinssatzText enabled=false");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box MitTiteldruckSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("smartfield MitTitel text=MitTiteldruck mandatory=true code=KOTiteldruck value_type=\"java.lang.Integer\" {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic event=changed placement=server {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("\"System.out.println(\\\"server call MitTitelFieldChanged\\\");");
      _builder.newLine();
      _builder.append("\t\t\t\t ");
      _builder.append("return formData;\"");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic event=changed placement=client {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("\"evaluateBuchungstext1And2();\"");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box DepotSequence master=MitTitel\t{");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("logic event=master_changed placement=client {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("\"Integer newMasterValue = form.getMitTitelField().getValue();");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("if (newMasterValue != null) {");
      _builder.newLine();
      _builder.append("\t\t      ");
      _builder.append("if (newMasterValue.equals(1)) {");
      _builder.newLine();
      _builder.append("\t\t        ");
      _builder.append("// in case \\\"Mit Titeldruck\\\" is selected we disable the depotField");
      _builder.newLine();
      _builder.append("\t\t        ");
      _builder.append("form.getDepotField().setEnabled(false);");
      _builder.newLine();
      _builder.append("\t\t        ");
      _builder.append("form.getDepotField().setMandatory(false);");
      _builder.newLine();
      _builder.append("\t\t      ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t      ");
      _builder.append("else {");
      _builder.newLine();
      _builder.append("\t\t        ");
      _builder.append("form.getDepotField().setEnabled(true);");
      _builder.newLine();
      _builder.append("\t\t        ");
      _builder.append("form.getDepotField().setMandatory(true);");
      _builder.newLine();
      _builder.append("\t\t      ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t    ");
      _builder.append("}\"");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("smartfield Depot text=DepotText lookup=DepotNumber value_type=\"java.lang.Double\" {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic exec=ZregAsMasterField");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box AlteNeueKONrSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("smartfield ObligationNrAlt text=AlteNeueKONr mandatory=true lookup=OldObliNumber value_type=\"java.lang.Integer\" {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic exec=ZregAsMasterField");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("long ObligationNr enabled=false label_visible=false");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("  ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box DatumEmissionSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("date BuchungsDatum text=DatumEmission enabled=false {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic event=init placement=client {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("\"form.getBuchungsDatumField().setValue(new java.util.Date());\"");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    \t");
      _builder.append("date EmissionsDatum mandatory=true label_visible=false {");
      _builder.newLine();
      _builder.append("    \t\t");
      _builder.append("logic event=init placement=client {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("\"form.getEmissionsDatumField().setValue(new java.util.Date());\"");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic event=changed placement=server {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("\"System.out.println(\\\"server call EmissionsDatumFieldChanged\\\");");
      _builder.newLine();
      _builder.append("\t\t\t\t ");
      _builder.append("return formData;\"");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    \t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box ZinstermAuslaufSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("string Zinsterm text=ZinstermAuslauf enabled=false");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("string EndJahr enabled=false label_visible=false");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("  ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box BetragSpesenSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("long Betrag text=BetragSpesen mandatory=true {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic event=changed placement=client {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("\"form.getEmissionField().setValue(0d);\"");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("string BetragsWaehrung enabled=false label_visible=false {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic placement=inline event=format_value {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("\"return TEXTS.get(\\\"CHF\\\");\"");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("  ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box EmissionsabgabeSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("double Emission text=Emissionsabgabe enabled=false");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("string EmissionsWaehrung enabled=false label_visible=false {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic placement=inline event=format_value {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("\"return TEXTS.get(\\\"CHF\\\");\"");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("  ");
      _builder.newLine();
      _builder.append("  \t");
      _builder.append("sequence_box KontobelastungSequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("smartfield KontoNr text=Kontobelastung mandatory=true lookup=KontoByZrnr value_type=\"java.util.List\" {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic exec=ZregAsMasterField");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("logic event=changed placement=client {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("\"KontoData kontoData = form.getKontoNrField().getValue();");
      _builder.newLine();
      _builder.append("\t\t\t    ");
      _builder.append("if (kontoData != null) {");
      _builder.newLine();
      _builder.append("\t\t\t      ");
      _builder.append("form.getZregKurzbezeichnungField().setValue(kontoData.getZregKurzBez());");
      _builder.newLine();
      _builder.append("\t\t\t      ");
      _builder.append("form.getKontostandField().setValue(kontoData.getSaldo());");
      _builder.newLine();
      _builder.append("\t\t\t    ");
      _builder.append("}\"");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("string ZregKurzbezeichnung enabled=false label_visible=false master=KontoNr ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("string Kontostand enabled=false label_visible=false");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box Buchungstext1Sequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("string KontoText1 text=Buchungstext1 enabled=false");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("  ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box Buchungstext2Sequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("string KontoText2 text=Buchungstext2 enabled=false");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("  ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sequence_box Buchungstext3Sequence {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("string KontoText3 text=Buchungstext3");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("} // end form Rka001");
      _builder.newLine();
      Model _parse = this._parseHelper.parse(_builder, resourceSet);
      this._validationTestHelper.assertNoErrors(_parse);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("module ch.raiffeisen.dialba.common");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("translation BuDatum de=\"Bu-Datum\"");
      _builder_1.newLine();
      _builder_1.append("translation Text de=\"Text\"");
      _builder_1.newLine();
      _builder_1.append("translation Valuta de=\"Valuta\"");
      _builder_1.newLine();
      _builder_1.append("translation Sy de=\"Sy\"");
      _builder_1.newLine();
      _builder_1.append("translation CpNr de=\"Cp.-Nr.\"");
      _builder_1.newLine();
      _builder_1.append("translation SollHaben de=\"Soll/Haben\"");
      _builder_1.newLine();
      _builder_1.append("translation Saldo de=\"Saldo\"");
      _builder_1.newLine();
      _builder_1.newLine();
      _builder_1.append("form Rka021_gen {");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("logic event=modify_load placement=server {");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("\"System.out.println(\\\"Rka021 form startup\\\");");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("formData.getStornoTable().addRow(new Object[]{new Date(), \\\"text\\\", new Date(), 15, 134592, \\\"sollhaben text\\\", 135.25});");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("return formData;\"");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("table StornoTable label_visible=false grid_height=10 grid_width=2 {");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("menu InfoF7Menu text=InfoF7");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("column ColBuDatum text=BuDatum type=date width=100");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("column ColText text=Text type=string width=138");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("column ColValuta text=Valuta type=date width=100 visible=false");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("column ColSy text=Sy type=int width=27");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("column ColCpNr text=CpNr type=int width=53");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("column ColSollHaben text=SollHaben type=string width=222");
      _builder_1.newLine();
      _builder_1.append("\t\t");
      _builder_1.append("column ColSaldo text=Saldo type=double width=160");
      _builder_1.newLine();
      _builder_1.append("\t");
      _builder_1.append("}");
      _builder_1.newLine();
      _builder_1.append("}");
      _builder_1.newLine();
      Model _parse_1 = this._parseHelper.parse(_builder_1, resourceSet);
      this._validationTestHelper.assertNoErrors(_parse_1);
    } catch (Exception _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
