/*
* generated by Xtext
*/
package org.eclipse.scout.saml.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SamlOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
