/*
 * generated by Xtext
 */
package org.eclipse.scout.saml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SamlRuntimeModule extends org.eclipse.scout.saml.AbstractSamlRuntimeModule {

}
