/*
 * generated by Xtext
 */
package org.eclipse.scout.saml;

import org.eclipse.scout.saml.converter.SamlConverter;
import org.eclipse.scout.saml.generator.SamlGenerator;
import org.eclipse.scout.saml.scoping.SamlScopeProvider;
import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.scoping.IScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SamlRuntimeModule extends org.eclipse.scout.saml.AbstractSamlRuntimeModule {
  @Override
  public Class<? extends IGenerator> bindIGenerator() {
    return SamlGenerator.class;
  }

  @Override
  public Class<? extends IScopeProvider> bindIScopeProvider() {
    return SamlScopeProvider.class;
  }

  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return SamlConverter.class;
  }

  /*@Override
  public Class<? extends ITypeProvider> bindITypeProvider() {
    return SamlTypeProvider.class;
  }*/
}
