/*
 * generated by Xtext
 */
package org.eclipse.scout.saml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SamlUiModule extends org.eclipse.scout.saml.ui.AbstractSamlUiModule {
	public SamlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
