/*
* generated by Xtext
*/
package org.eclipse.scout.saml;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SamlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.scout.saml.ui.internal.SamlActivator.getInstance().getInjector("org.eclipse.scout.saml.Saml");
	}
	
}
